# Generated by Django 4.2.5 on 2024-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('running_out', 'Running Out'), ('expired', 'Expired')], default='in_stock', max_length=20)),
            ],
        ),
    ]
