# Generated by Django 5.1.1 on 2024-11-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_rename_img_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
