# Generated by Django 5.1.1 on 2024-11-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_cart_user_id_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, choices=[('chuaThanhToan', 'Chưa thanh toán'), ('daThanhToan', 'Đã thanh toán'), ('dangGiaoHang', 'Đang giao hàng'), ('daGiaoHang', 'Đã giao hàng')], default='chuaThanhToan', max_length=20, null=True),
        ),
    ]
