# Generated by Django 4.2.5 on 2024-11-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
    ]
